# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicaps', '0001_initial_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='grade',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
